spring:
  config:
    activate:
      on-profile: supabase
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_SERVICE_KEY}

app:
  upload:
    dir: ${java.io.tmpdir}/pgf-uploads

server:
  port: 8080

# Logs pour debug initial
logging:
  level:
    com.pgf: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.flywaydb: DEBUG